// Base de datos de películas y series de CineMax MX
const MOVIES = [
  {
    "id": 1,
    "title": "El Último Imperio",
    "genre": "Ciencia Ficción",
    "year": 2026,
    "rating": 8.7,
    "duration": "2h 18min",
    "type": "Película",
    "yt": "dQw4w9WgXcQ",
    "emoji": "🎬",
    "desc": "En un México del futuro cercano, un joven hacker descubre que los cimientos del poder ocultan un secreto que podría cambiarlo todo. Una historia de traición, redención y revolución.",
    "badge": "TENDENCIA",
    "episodes": []
  },
  {
    "id": 2,
    "title": "Oops, Me Casé con un Multimillonario",
    "genre": "Romance",
    "year": 2026,
    "rating": 9,
    "duration": "1h 15min",
    "type": "Película",
    "yt": "JBVn1HhTxbA",
    "emoji": "🎬",
    "desc": "Una madre soltera busca empleo como niñera y termina casándose en una cita a ciegas apresurada. Junto a dos infantes y un cónyuge aparentemente humilde, enfrenta desafíos sociales y familiares mientras oculta identidades reales, desatando una serie de malentendidos y revelaciones sorprendentes sobre el estatus económico de su nueva familia.",
    "badge": "NUEVO",
    "episodes": [],
    "thumb": "https://i3.ytimg.com/vi/JBVn1HhTxbA/maxresdefault.jpg"
  },
  {
    "id": 3,
    "title": "Velocidad Extrema 9",
    "genre": "Acción",
    "year": 2026,
    "rating": 7.5,
    "duration": "2h 02min",
    "type": "Película",
    "yt": "dQw4w9WgXcQ",
    "emoji": "🚗",
    "desc": "El equipo de carreras más peligroso del mundo se enfrenta a su misión más imposible.",
    "badge": "POPULAR",
    "episodes": []
  },
  {
    "id": 4,
    "title": "Mi Familia Manda",
    "genre": "Comedia",
    "year": 2026,
    "rating": 8.4,
    "duration": "1h 45min",
    "type": "Película",
    "yt": "dQw4w9WgXcQ",
    "emoji": "😂",
    "desc": "Una familia disfuncional de cinco hermanos debe unirse para salvar el negocio familiar de tacos antes de la gran feria.",
    "badge": "NUEVO",
    "episodes": []
  },
  {
    "id": 5,
    "title": "Las Alas del Tiempo",
    "genre": "Drama",
    "year": 2026,
    "rating": 9,
    "duration": "2h 22min",
    "type": "Película",
    "yt": "dQw4w9WgXcQ",
    "emoji": "🌅",
    "desc": "Una madre migrante cruza tres países para reunirse con sus hijos. Historia basada en hechos reales.",
    "badge": "PREMIADO",
    "episodes": []
  },
  {
    "id": 6,
    "title": "La Casa del Cerro Negro",
    "genre": "Terror",
    "year": 2026,
    "rating": 8.3,
    "duration": "1h 44min",
    "type": "Película",
    "yt": "dQw4w9WgXcQ",
    "emoji": "👻",
    "desc": "Un grupo de amigos llega a una mansión abandonada en las montañas de Puebla. No todos regresarán.",
    "badge": "NUEVO",
    "episodes": []
  },
  {
    "id": 7,
    "title": "Xólotl: El Perro del Inframundo",
    "genre": "Terror",
    "year": 2026,
    "rating": 8.5,
    "duration": "1h 52min",
    "type": "Película",
    "yt": "dQw4w9WgXcQ",
    "emoji": "🐕",
    "desc": "La antigua deidad azteca despierta en el metro de Ciudad de México. El inframundo reclama su tributo.",
    "badge": "TENDENCIA",
    "episodes": []
  },
  {
    "id": 8,
    "title": "Cartel: La Serie",
    "genre": "Series",
    "year": 2026,
    "rating": 9.2,
    "duration": "45min/ep",
    "type": "Serie",
    "yt": "dQw4w9WgXcQ",
    "emoji": "🌵",
    "desc": "El ascenso y caída de una familia que controlaba el comercio más oscuro de México. 8 episodios por temporada.",
    "badge": "T2 NUEVA",
    "episodes": [
      "Episodio 1",
      "Episodio 2",
      "Episodio 3",
      "Episodio 4",
      "Episodio 5",
      "Episodio 6",
      "Episodio 7",
      "Episodio 8"
    ]
  },
  {
    "id": 9,
    "title": "La Fiscalía",
    "genre": "Series",
    "year": 2026,
    "rating": 8.9,
    "duration": "52min/ep",
    "type": "Serie",
    "yt": "dQw4w9WgXcQ",
    "emoji": "⚖️",
    "desc": "Una fiscal incorruptible enfrenta a los poderes fácticos de la Ciudad de México en su búsqueda por justicia.",
    "badge": "NUEVO",
    "episodes": [
      "Episodio 1",
      "Episodio 2",
      "Episodio 3",
      "Episodio 4",
      "Episodio 5",
      "Episodio 6",
      "Episodio 7",
      "Episodio 8",
      "Episodio 9",
      "Episodio 10"
    ]
  },
  {
    "id": 10,
    "title": "Neon Barrio",
    "genre": "Series",
    "year": 2025,
    "rating": 8.5,
    "duration": "38min/ep",
    "type": "Serie",
    "yt": "dQw4w9WgXcQ",
    "emoji": "🌆",
    "desc": "Jóvenes artistas en el México cyberpunk de 2060 luchan por sobrevivir y tạo ra nghệ thuật trong thế giới doanh nghiệp.",
    "badge": "",
    "episodes": [
      "Episodio 1",
      "Episodio 2",
      "Episodio 3",
      "Episodio 4",
      "Episodio 5",
      "Episodio 6"
    ]
  },
  {
    "id": 11,
    "title": "Chefs de Guerra",
    "genre": "Series",
    "year": 2026,
    "rating": 8,
    "duration": "42min/ep",
    "type": "Serie",
    "yt": "dQw4w9WgXcQ",
    "emoji": "👨‍🍳",
    "desc": "Diez chefs mexicanos compiten por el título del mejor restaurante del país. Cada plato cuenta una historia.",
    "badge": "POPULAR",
    "episodes": [
      "Episodio 1",
      "Episodio 2",
      "Episodio 3",
      "Episodio 4",
      "Episodio 5",
      "Episodio 6",
      "Episodio 7",
      "Episodio 8"
    ]
  },
  {
    "id": 12,
    "title": "Creen que es un mendigo común, pero es Dios de la Guerra que vence a mil; bella señorita se enamora",
    "genre": "Acción",
    "year": 2026,
    "rating": 9.2,
    "duration": "1h 55min",
    "type": "Película",
    "yt": "TooF1IQyoZQ",
    "thumb": "https://i3.ytimg.com/vi/TooF1IQyoZQ/maxresdefault.jpg",
    "desc": "El Maestro Supremo | Peliculas Completas | Estreno 2026 Mejor Películas de Acción en Español",
    "badge": "NUEVO",
    "episodes": []
  }
];
