name = "cinemx"
compatibility_date = "2026-07-02"
main = "worker.js"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "cinemax-movies"
database_id = "9a69dcf6-66d5-4be1-bd16-b9bc13a5f9fb"
migrations_dir = "migrations"

[[send_email]]
name = "SEND_EMAIL"
destination_address = "tuanlinhnguyen765@gmail.com"

[[durable_objects.bindings]]
name = "CINEMAX_VIEW_COUNTER"
class_name = "MovieViewCounter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MovieViewCounter"]
